# Generated by Django 4.1 on 2022-09-23 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name', max_length=256)),
                ('gender', models.CharField(blank=True, help_text='Gender', max_length=10)),
                ('dob', models.DateField(blank=True, help_text='DOB', max_length=20)),
                ('country_code', models.CharField(blank=True, help_text='Country Code', max_length=6)),
                ('mobile', models.CharField(blank=True, help_text='Mobile Number', max_length=11)),
                ('created_from', models.CharField(blank=True, help_text='Created From', max_length=255)),
                ('active_user', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'abstract': False,
            },
        ),
    ]
