# Generated by Django 4.1 on 2022-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name', max_length=256)),
                ('complete_name', models.CharField(blank=True, help_text='Complete Name', max_length=256)),
            ],
        ),
    ]
