# Generated by Django 4.1 on 2022-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_customercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercategory',
            name='num_orders',
            field=models.IntegerField(default=0, verbose_name='Number of Orders'),
        ),
    ]
