# Generated by Django 4.1 on 2022-09-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_customercategory_num_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercategory',
            name='num_orders',
        ),
        migrations.AddField(
            model_name='customercategory',
            name='num_orders_from',
            field=models.IntegerField(default=0, verbose_name='Number of Orders From'),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='num_orders_to',
            field=models.IntegerField(default=0, verbose_name='Number of Orders To'),
        ),
    ]
