# Generated by Django 4.1 on 2022-09-24 08:32

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0008_alter_customercategory_complete_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, default=ecommerce.models.create_new_ref_number, max_length=16, unique=True, verbose_name='Order No.')),
                ('customer_name', models.CharField(help_text='Name', max_length=256)),
                ('customer_phone', models.CharField(max_length=12, verbose_name='Customer Phone')),
                ('customer_address', models.CharField(blank=True, max_length=256, verbose_name='Customer Address')),
                ('create_date', models.DateTimeField(blank=True, verbose_name='Create Date')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Discount')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Tax Amount')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Total Amount')),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Subtotal Amount')),
                ('order_quantity', models.IntegerField(default=1, verbose_name='Order Quantity')),
                ('payment_type', models.CharField(blank=True, max_length=256, verbose_name='Payment Type')),
                ('banking_type', models.CharField(blank=True, max_length=256, verbose_name='Other Payment')),
                ('banking_image', models.ImageField(blank=True, default='banking.png', help_text='Banking Slip Image', null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='banking')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
    ]
