# Generated by Django 4.1 on 2022-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deli_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, verbose_name='Delivery Charges'),
        ),
    ]
