# Generated by Django 4.1 on 2022-09-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_order_status_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_state',
            field=models.CharField(choices=[('Abu_Dubai', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Ras_Al_Khaimah', 'Ras Al Khaimah')], default='Dubai', max_length=256, verbose_name='Customer State'),
        ),
    ]
