# Generated by Django 4.1 on 2022-09-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_userprofile_customer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='customer_category',
        ),
    ]
