# Generated by Django 4.1 on 2022-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_remove_userprofile_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_category',
            field=models.CharField(blank=True, help_text='Customer Category', max_length=255),
        ),
    ]
